version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - LIGHTHOUSE_URL=https://aniwave.to/home
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
